### ISSUE TITLE
Provide documentation describing how to migrate to this new version of slack.

### ISSUE THREAD

**Issue by janvda** [travisghansen/node-red-slack#1]
It would be good that you provide migration documentation so that the people using slack version 1.2.0 know how they can migrate their existing flows to the new flow.

1. FYI The existing `slack` node has the following documentation:

> Sends the msg.payload to Slack.
> Simple way to post to a Slack channel.
> You can optionally override the destination channel if required - either in the edit dialogue or by setting msg.channel.
> You can also create Slack attachments by adding a msg.attachments property that must be an array.

The following node properties can be set for this node:
1. WebHook URL
2. Posting UsreName
3. Emoji Icon
4. Channel (= optional)
5. Name (= name of the node in the node-red editor).

2. FYI the existing `Slack Bot in`  node has the following documentation:

> Provides a listener in any channel the Slack bot is a member of.
> Outputs the msg.payload as the incoming message.
> Outputs msg.SlackObj with full Slack message details.
> You can optionally limit the channel to listen to in the edit dialogue.

The following node properties can be set for this node:
1. My Bot API Token
2. Channel (= optional)
3. Name (= name of the node in the node-red editor)

3. FYI the existing `Slack Bot Out` node has the following documentation:

> Sends the msg.payload to Slack based on the Bot API token provided.
> 
> You can optionally override the destination channel if required - either in the edit dialogue or by setting msg.channel.

The following node properties can be set for this node:
1. My Bot API Token
2. Channel (= optional)
3. Name  (= name of the node in the node-red editor)

**Comment by travisghansen** [comment]
@janvda have a look at the updated docs and let me know if the migration section is helpful.

**Comment by janvda** [comment]
Yes the migration section is certainly very helpful.

1.  I would change the title from "migration from 0.x.y" into "migration from 1.2.0 or earlier".
2. In the "Install" section I would add a note that this version is no longer backwards compatible with the previous version and refer to the migration section.
3. Under the migration section I would change the titles into something as follows
- Replace old `slack` node by new `slack web out` node
- Replace old `Slack Bot In` node by new `slack rtm in` node
- Replace old `Slack Bot Out` node by new `slack rtm out` node

**Comment by travisghansen** [comment]
I've provided further clarification.

**Comment by janvda** [comment]
Looks very good.
one little typo in the title: `migration from 0.1.2 or ealier`
should be `migration from 0.1.2 or earlier`

**Comment by travisghansen** [comment]
Good catch! I'll get that updated and make sure the links still work.

**Comment by travisghansen** [comment]
Fixed the typo.

**Comment by janvda** [comment]
I consider this issue closed - thanks a lot !!
