### ISSUE TITLE
slack-client is deprecated

### ISSUE THREAD

**Issue by ozomer** [travisghansen/node-red-slack#11]
npm warning `slack-client` is deprecated. Use [@slack/client](https://www.npmjs.com/package/@slack/client) instead.

**Comment by janvda** [comment]
I also get this warning when installing this node.
More precisely I get following warning:
`npm WARN deprecated slack-client@1.5.1: Use @slack/client instead, this package is no longer maintained`

**Comment by yayadrian** [comment]
Closing this issue as it is resolved in version 2.0.0
