### ISSUE TITLE
Slack Bot API token is saved in flows json file instead in flows credentials json file.

### ISSUE THREAD

**Issue by janvda** [travisghansen/node-red-slack#18]
Hi,

The Slack Bot API token is saved in flows json file instead in flows credentials json file.

This is problem when
- trying to share your nodered flows file OR
- using the latest nodered project feature where you can publish your flows on github.
as in that case you are also sharing the Slack Bot API token.

Not also that once you publish the slack bot token on github - that this token will be disabled automatically as there is slack tool that is checking if any slack token is shared on github !!

This token should be stored in the flows credentials json file as specified in https://nodered.org/docs/creating-nodes/credentials

kr
Jan.

**Comment by travisghansen** [comment]
Resolved by `2.0.0`.
