### ISSUE TITLE
slack webhook URL is saved in flows json file instead of credential flows json file

### ISSUE THREAD

**Issue by janvda** [travisghansen/node-red-slack#19]
Hi,

The slack webhook URL is saved in flows json file instead of the flows credentials json file.

This is problem when
- trying to share your nodered flows file OR
- using the latest nodered project feature where you can publish your flows on github.
as in that case you are also sharing the slack webhook URL which allows everyone to read and post messages on your slack workspace.

This URL (or at least the last part) should be stored in the flows credentials json file as specified in https://nodered.org/docs/creating-nodes/credentials

kr
Jan.

**Comment by travisghansen** [comment]
Resolved by `2.0.0`
