### ISSUE TITLE
How to use "link_names"?

### ISSUE THREAD

**Issue by Swiftnesses** [travisghansen/node-red-slack#33]
Hello,

I've successfully posted to a channel, but would like to 'tag' a user in the message.

I tried to added "link_names: true" as part of the payload hoping it would help (as per the slack instructions), but no cigar, any ideas how I can tag a user in a message?

Thanks in advance :)

**Comment by travisghansen** [comment]
Try this:

```
payload = '<!channel> shhh, everyone be quiet, <@' + msg.payload.userObject.name + '> has something important to say..';
```

The above is variable and linked to a user `user_typing` event so it's variable but should work with hard-coded values as well.

**Comment by Swiftnesses** [comment]
Hi,

Apologies, I tried the above but it returned undefined... Would this be used with the slack-web-out node? I was hoping there's something I could add to:

```
var topic = "chat.postMessage";

var payload = {
    "channel": "#dev-integration-updates",
    "text": "<@Mark> Hi from our custom slack bot built on Node Red :muscle:"
}

msg = {
  topic: topic,
  payload: payload
}

return msg
```

Which would enable username linking, the Slack API refers to adding link_names, but this doesn't seem to work in my case.

**Comment by travisghansen** [comment]
Can you send over the first few characters of the token you’re using? You may not have a token with all the needed permissions..
