### ISSUE TITLE
Flows

### ISSUE THREAD

**Issue by planet4** [travisghansen/node-red-slack#38]
I have some issues with scopes or maybe I am just stupid. It would be great if there were some flows you could share. That would make this much easier to understand.

**Comment by travisghansen** [comment]
Do you have a bot token? What does the first 5 or so chars of the token look like?

**Comment by planet4** [comment]
Thanks for replying. I have made some progress. It seems like Slack-RTM only work with the old bots tokens. And sending from the slack-web-out does not work when using the old bot token with old scopes. I have now two Slack apps, One new and one old. It works. My goal is to use the api to change users profile images with our general ones stored in our Azure AD. However sharing some flows with examples would be good as I still struggle to get it working,

**Comment by travisghansen** [comment]
Bot token should work fine for the http out methods. Maybe send me the specific api call you’re trying to use and I can help with an example.

**Comment by planet4** [comment]
I think it is more my lack of knowledge that is causing my problems. I am getting closer. I just have problems with the regex now.

// check for keyword
// could use regex etc
if (!msg.payload.text.includes("one", "two", "three")) {
    return null;
}

I can only trigger at one word.

**Comment by travisghansen** [comment]
I would probably check out this: https://www.w3schools.com/jsref/jsref_some.asp

Let me know if you can't get it!
