### ISSUE TITLE
Invalid Token & Disconnected (does this plug-in work?)

### ISSUE THREAD

**Issue by bluemonkeydev** [travisghansen/node-red-slack#41]
I've tried every possible combination and had no luck getting this plug-in to work. I did use the previous version without any issues.

I created a brand-new slack app, 'incoming-webhook' permissions, "reinstalled to workspace", copy the bot user outh token into node-red and deployed. Nothing, just errors.

I read through all of the issues and none seem to mention any other steps.

![image](https://user-images.githubusercontent.com/1980947/100547268-73a35a80-322b-11eb-8f46-28e58c0c84f0.png)

![image](https://user-images.githubusercontent.com/1980947/100547238-3d65db00-322b-11eb-900b-0fd41daef4df.png)

![image](https://user-images.githubusercontent.com/1980947/100547248-51a9d800-322b-11eb-9c20-08b218a186a6.png)

![image](https://user-images.githubusercontent.com/1980947/100547258-5d959a00-322b-11eb-8519-d5460fc66b72.png)

**Comment by travisghansen** [comment]
Slack has been progressively pushing away from the old style bot tokens (the best ones to use for this node). Can you try the instructions here: https://github.com/yayadrian/node-red-slack/issues/29

I assure you the node works perfectly well when slack likes your token :D

**Comment by bluemonkeydev** [comment]
Gottcha - thanks for the update.
