### ISSUE TITLE
Transfer repo/ownership

### ISSUE THREAD

**Issue by travisghansen** [travisghansen/node-red-slack#44]
Would you be interested in transferring this and the npm repo over to me for continued maintenance?

**Comment by yayadrian** [comment]
Hi @travisghansen Yes would be totally happy to do this. I don't want it to die but currently am unable to support it. 
I'll send you a request.

**Comment by yayadrian** [comment]
@travisghansen I can't currently transfer this repo as you already have repo with the same name. Are you able to rename your current/old one?

**Comment by travisghansen** [comment]
Done.

**Comment by travisghansen** [comment]
How would you prefer to figure out the npm aspect? Did you have any automation to push builds or were you just doing that from your workstation?

**Comment by travisghansen** [comment]
@yayadrian how can we get this transferred on npm? I'll be ready to make some updates in the next couple weeks.

**Comment by yayadrian** [comment]
Sorry for the delay. Have an open support request with NPN as I can't currently access my old account. Will keep you posted.

**Comment by travisghansen** [comment]
Got the invite and should be good to go at this point. Thanks!
